theforeman/puppet-puppet

Gemfile, spec/classes/puppet_agent_service_spec.rb, spec/classes/puppet_config_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_service_spec.rb, spec/classes/puppet_server_spec.rb
The repo's tagged, but gem has yet to be released, so this is pre-emptive based on https://github.com/rodjek/rspec-puppet/commit/8459e14.
It might be best to pin at ~> 1.0 for the time being, instead of >= 1?
More PRs:
- https://github.com/theforeman/puppet-foreman/pull/259
- https://github.com/theforeman/puppet-tftp/pull/23
- https://github.com/theforeman/puppet-dhcp/pull/28
- https://github.com/theforeman/puppet-foreman_proxy/pull/129
- https://github.com/theforeman/foreman-installer-modulesync/pull/6
=> Update error raising tests and use of subject for rspec-puppet 2.0

manifests/init.pp, manifests/params.pp, manifests/server/rack.pp, spec/classes/puppet_server_rack_spec.rb, spec/lib/module_spec_helper.rb, templates/server/config.ru.erb
* Default is an empty array
* Elements are added to ARGV in Puppet server's rack config.ru
This is an ugly work around to segfaults that occur when running Puppet under Passenger in Ruby 1.8.7 (CentOS 6.x).  The only way I've found to work around the segfaults is to enable profiling by appending the "--profile" flag to ARGV in config.ru.
=> Add parameter server_rack_arguments

manifests/init.pp, manifests/params.pp, manifests/server/config.pp
Instead of including foreman::params, the values are copied. That means 
foreman::params no longer needs to be included.
The next use of foreman is in puppet::server::config where it sets up 
reporting and ENC. This is wrapped in a new boolean $server_foreman. The user
will still need to take care of clearing $server_reports and
$server_external_nodes.
Fixes #154
=> Make foreman integration optional

.fixtures.yml, README.md, manifests/init.pp, manifests/params.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
more a WIP for discussion. comments please :newspaper:
=> add PuppetDB configuration on puppet master side

README.md, metadata.json
Following the change for theforeman/foreman and puppetlabs/puppetdb.
=> Make theforeman/git a soft dependency

manifests/init.pp, manifests/params.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
Make the node.rb timeout configurable. This is useful for use cases when
catalog compilation takes more time and/or the node.rb request to
Foreman is being handled by a freshly spawned Passenger worker.
=> Fixes #9286 - node.rb timeout too low and not configurable

manifests/config.pp, manifests/init.pp, manifests/params.pp, manifests/server/config.pp, manifests/server/env.pp, manifests/server/install.pp, metadata.json, spec/classes/puppet_config_spec.rb, templates/puppet.conf.erb, templates/server/config.ru.erb
For the master configuration there's more stuff missing from puppetlabs-apache, so that's not going to happen for now.
The server_vardir parameter is gone, which is theoretically OK because the version is bumped anyway. puppet-foreman_proxy would need to be updated in one line where this is used as default for a puppet_home setting.
=> FreeBSD agent support

manifests/agent/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_agent_config_spec.rb
We want to be able to get around puppet locking system using `--agent_disabled_lockfile /nonexisting`, but by default the puppet lock is removed on Debian.
This patch will allow us to set `remove_lock` to false.
=> Add remove_lock parameter

manifests/params.pp
On local, $::puppetmaster is not set, which errors out with strict variables.
=> Fixes puppet apply with strict_variables

manifests/server/config.pp
Pre-req to fixing theforeman/puppet-foreman#129 and removing ordering and
implicit dependency of foreman::puppetmaster on theforeman/puppet-puppet.
=> Anchor Foreman puppet master configuration inside server::config

README.md, manifests/init.pp, manifests/params.pp, manifests/server/passenger.pp
(load balancer/reverse proxy scenarios), protected by default Deny all. Configurable listen port and allow directive.
=> Add options to let the puppet master listen for HTTP connections too

manifests/server/passenger.pp
So, slightly embarrassing, but due to the way the puppetlabs/apache module handles Order, Allow and Deny between versions 2.2/2.4, the fact that when you specify no allowed hosts, all hosts are allowed somehow slipped through. This PR should fix it by actually forcing the puppetlabs/apache module to change the Order directive to Deny, Allow by default, then adding it again for good measure, denying all again and THEN adding allowed hosts again.
Slightly convoluted, but the best I can do with the current Apache 2.2/2.4 Order/Allow/Deny thing.
=> Fix all hosts allowed in HTTP puppetmaster

manifests/init.pp, manifests/params.pp, manifests/server/install.pp
When installing puppetserver the numbers do not progress in step with puppet client versions.
=> Allow setting separate version for puppet server and client packages

.fixtures.yml, manifests/agent/config.pp, manifests/config.pp, manifests/server/config.pp, manifests/server/env.pp, metadata.json, spec/classes/puppet_agent_config_spec.rb, spec/classes/puppet_agent_install_spec.rb, spec/classes/puppet_agent_spec.rb, spec/classes/puppet_config_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_config_spec.rb, spec/defines/puppet_server_env_spec.rb
This works with either puppetlabs-concat 1.2.x or 2.x so can be merge without waiting for dependencies to be compatible with puppetlabs-concat 2.x IMHO.
=> Use puppetlabs-concat instead of theforeman-concat_native

manifests/init.pp, manifests/params.pp, templates/agent/puppet.conf.erb
Currently the environment set in puppet.conf comes from the top scope
variable. If we launch puppet with '--environment foo' for testing, it
changes the puppet.conf file (what we do no want). We used to override
$environment somewhere in our stack with the fixed environment so that
it work as expected thanks to dynamic scoping still functionnal in ERB
templates. But this workaround does not work anymore with the future
parser now they remove totally dynamic scoping.
This patch allows to set the environment in the puppet class.
=> Add environment parameter

manifests/init.pp
Untested, but should fix http://ci.theforeman.org/job/systest_foreman/6421/tapResults/
[FATAL 2015-05-26 13:50:01 fatal] Unable to continue because of: undocumented parameters in puppet: environment
=> Document environment parameter

manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb, spec/defines/puppet_server_env_spec.rb
Sorry about the refactor in the middle, the file was a bit of a mess - but I can remove it if needed.
The umask ensures the cert generation works properly under a restrictive umask, as the Puppet CA doesn't enforce file permissions.  The agent does though, which means running the agent during/after installation can make it work as it tidies some file permissions.
=> Set exec umask on Puppet 3.4+ for cert generation

manifests/params.pp, spec/classes/puppet_server_config_spec.rb
Hi! recently I noticed that the classfile parameter is pointing to the wrong place:
The documentation states that it should be set by default to ```$statedir/classes.txt``` 
I ran into a weird problem where MCollective could not find node based on classes because it was looking at the default file path, while this module sets it to a really old default.
The Mcollective documentation (from puppetlab) states:
> Puppet provides a list of classes applied to a node by default in /var/puppet/state/classes.txt or  /var/lib/puppet/state/classes.txt (depending on which Puppet version you are using. The latter is true for 0.25.5 onwards) , we’ll use this data with –with-class filters.
Thank you!
=> classfile should default to /classes.txt

templates/auth.conf.erb
auth.conf changed in puppet 4: https://github.com/puppetlabs/puppet/blob/4.0.0/conf/auth.conf
This pull requests adds support for puppet 4 agents while maintaing backwards compatability for puppet 3 agents, see http://docs.puppetlabs.com/puppetserver/latest/compatibility_with_puppet_agent.html#transfer-and-modify-custom-authconf-rules for more info
=> puppet 4 support for auth.conf

manifests/config.pp, spec/classes/puppet_config_spec.rb
by adding the missing parameter to the puppet::config class, the pluginfactsource source variable is now correctly set in puppet.conf.
This change is required to make the code from #212 work.
=> pluginfactsource is not correctly set when using srv records

README.md
We need to revistit that, once puppet(master) 4.x gets supported by us.
=> puppetlabs-puppetdb 5.x is incompatible

manifests/init.pp
I think this is the reason the nightly RPM build failed: http://ci.theforeman.org/job/packaging_build_rpm/2082/console
Ah yes, installers are now failing at runtime with:
[FATAL 2015-07-23 07:50:06 fatal] Unable to continue because of: undocumented parameters in puppet: sharedir
=> Document sharedir parameter

manifests/config.pp, manifests/server/config.pp, manifests/server/install.pp
This matches the puppet default and it reduces differences if you set a
global default in site.pp.
=> Set explicit permissions and ownership

manifests/params.pp
Regression introduced in f74e45d1dc8a96929f22733f39052a798aeff52f.
=> Correct $puppetrun_cmd on Linux

manifests/server/config.pp
This PR addresses an error observed trying to run the module in standalone mode on a CentOS 7 host.  The module fails on missing $server_manifest_path, as that path is not created when puppet-agent is installed via yum prior to running the module.
Note this is for deployment of puppetserver v2.1 (aka puppet 4).
```
...
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/puppetlabs/code/manifests/site.pp20150825-2737-vftlyr.lock at 144:/home/myuser/puppettest/modules/puppet/manifests/server/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/puppetlabs/code/manifests/site.pp20150825-2737-vftlyr.lock at 144:/home/myuser/puppettest/modules/puppet/manifests/server/config.pp
Wrapped exception:
No such file or …
```
=> make sure server_manifest_path exists too

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_config_spec.rb, spec/classes/puppet_server_config_spec.rb, templates/puppet.conf.erb, templates/server/puppet.conf.erb
This pull allows setting the default_manifest configurable in puppet.conf as well as optionally managing the file and its contents. It also allows ssldir to not be set in the puppet.conf master section which is necessary when provisioning masters without the CA role (https://docs.puppetlabs.com/guides/scaling_multiple_masters.html#before-running-puppet-agent-or-puppet-master)
=> Adds 4 new class parameters to puppet main class

manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
This addresses #113 in part as it stops generating a CA cert for masters that don't have `server_ca` set to true.
Setting the DNS alt names correctly doesn't require any changes as `puppet cert --generate` will read the dns_alt_names settings from puppet.conf. Users only need to set that setting properly via `dns_alt_names` and the alt names will be in the certificate.
=> Don't generate CA cert if not a CA server

manifests/params.pp
Ensures that the HTTP requests from ENC/report processors work
correctly and don't receive a 404.
Follow-up of https://github.com/theforeman/puppet-foreman_proxy/pull/148
=> refs #8389 - lower case FQDN in foreman_url parameter

manifests/params.pp, spec/classes/puppet_agent_service_spec.rb, spec/classes/puppet_agent_service_systemd_spec.rb
Check specific versions of Debian and EL OSes to stop managing the
systemd timer, as a service resource with the systemd provider will
fail on older OS releases.
Fixes GH-334
=> Remove management of systemd timer unit on non-systemd OSes

manifests/agent/service.pp
Preserves ordering of the agent service(s) in relation to
puppet::agent::config etc.
Fixes GH-336
=> Contain service implementations inside puppet::agent::service

spec/defines/puppet_server_env_spec.rb
>/Users/weeks/Development/puppet-puppet/spec/defines/puppet_server_env_spec.rb:11: warning: duplicated key at line 14 ignored: :concat_basedir
Fixes this warning when running tests.
=> remove duplicate concat_basedir

manifests/params.pp, spec/classes/puppet_config_spec.rb
`$codedir` should only be used on Puppet 4, and the Puppet 3 default
should be using `$confdir`.  This failed on Puppet 3 tests with:
/Puppet::Server::Config/Exec[puppet_server_config-generate_ca_cert]/returns:
Error converting value for param 'hiera_config': Could not find value for $codedir
Follows up #356.
=> Swap hiera_config default values for Puppet 3.x and 4.x

manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
this will put the correct etc_dir into the foreman module config
to be used together with theforeman/puppet-foreman#413
=> set puppet_etcdir of foreman module

manifests/init.pp, manifests/params.pp, spec/classes/puppet_server_puppetserver_spec.rb, spec/classes/puppet_server_spec.rb, templates/server/puppetserver/conf.d/webserver.conf.erb
Such an attempt was done in the past (#200) but was very complex due to
the use of apache::vhost, which does mot allow mixing IP and non-IP
based vhosts.
This PR only takes care of the Puppetserver side and issues a warning if
users try to change the IP address with the puppetmaster implementation.
=> Allow to specify the listen ip address of the puppetserver

manifests/server/config.pp, manifests/server/puppetserver.pp
the issue was that the puppetserver tests included only ::puppet and ::puppet::server::puppetserver, but not ::puppet::server, which caused issues if ::puppet::server::puppetserver accessed variables from ::puppet::server such as in #364
Thanks to @roidelapluie
=> Make sure puppet::server is included in puppet::server::puppetserver

CHANGELOG.md, manifests/init.pp, manifests/params.pp, manifests/server/passenger.pp
@mmoll: Just some cleanup :-)
```passenger_max_pool``` is a global passenger setting which we do not want to support. The parameter is not passed through to puppetlabs-apache module and therefore has no effect.
=> remove useless parameter server_passenger_max_pool

manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb
This eases upgrades of puppetserver to 2.3, see
https://docs.puppet.com/puppetserver/2.3/release_notes.html#modifications-to-bootstrapcfg-might-cause-problems-during-upgrades-to-230
closes GH-373
=> add versioned-code-service on puppetserver >= 2.3

CHANGELOG.md, manifests/init.pp, manifests/params.pp, manifests/server/config.pp, spec/classes/puppet_config_spec.rb, spec/classes/puppet_server_config_spec.rb, templates/puppet.conf.erb, templates/server/puppet.conf.erb
Also to be used a base for #370. This breaks the API and has to go into #371 after merging. puppet-foreman_proxy also needs updating after this.
=> manage autosign file in puppet-puppet

manifests/config.pp, manifests/init.pp, manifests/params.pp, metadata.json, templates/namespaceauth.conf.erb
Replace `rescue` with `||` in namespaceauth template as it was probably intended.
=> Bump requirement of puppet to 3.1.0 and drop namespaceauth.conf.

manifests/server/env.pp, spec/defines/puppet_server_env_spec.rb, templates/server/environment.conf.erb, templates/server/puppet.conf.env.erb
The default value for modulepath of environments is always based on
`::puppet::server_envs_dir` regardless of the desired `basedir`.
This commit changes it so that the default modulepath is correctly based on the
value of basedir.
=> Use `basedir` to construct default modulepath in environment.

README.md, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/services.d/ca.cfg.erb
PS 2.5 moves CA configuration from bootstrap.cfg to a services.d/ca.cfg
file, separating user config (CA) from app config (e.g. versioned code
service). This is now configured instead of bootstrap.cfg when the
server_puppetserver_version parameter is set to 2.5.
A special version value of 2.4.99 (now the default) configures both the
2.4 and 2.5 files simultaneously, creating both bootstrap.cfg and
services.d/ca.cfg so the module works across both versions, albeit with
logged warnings about duplicate CA definitions. This ensures the module
will still work on the release of 2.5, after which time the parameter
default can be changed to 2.5.0 to remove the duplicate configuration.
=> fixes #15132 - support services.d/ configuration in Puppet Server 2.5

spec/classes/puppet_config_spec.rb, templates/auth.conf.erb
When using Puppet 4 without Puppet Server (i.e. Rack configuration),
the resource_types API is still required by the smart proxy and is
configured in the regular auth.conf.
=> Permit access to v3 resource_type API on Puppet 4

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/passenger.pp, spec/classes/puppet_server_passenger_spec.rb
This allows setting the PassengerRuby setting in the vhost configuration for puppet's rack application.
=> Add support for the PassengerRuby setting.

spec/classes/puppet_config_spec.rb, templates/auth.conf.erb
They are not working anyway, except with puppetserver (with legacy-routes-service).
Ref: https://docs.puppet.com/puppetserver/2.1/compatibility_with_puppet_agent.html#details-about-backwards-compatibility
... and add /puppet-ca/v1/certificate_revocation_list/ca endpoint.
=> Remove Puppet 3 endpoints when using Puppet 4

manifests/init.pp
manage_packages can be either a bool or string data type.
=> Fix Kafo data types on manage_packages/client_package

manifests/params.pp, manifests/server/install.pp, manifests/server/service.pp, spec/classes/puppet_server_service_spec.rb, spec/classes/puppet_server_spec.rb
@sathieu please test
4.5.2-1 packages are in the new queue for unstable at the moment, there were no changes that would affect this PR compared to 4.5.0-4.
=> support Debian non-AIO Puppet 4.x packages

templates/server/puppet.conf.main.erb
`basemodulepath` setting was indented two extra spaces more than it
should have been.
=> Fix indentation and whitespace in puppet.conf

README.md, manifests/params.pp
=> assume version 2.5.0 of puppetserver

manifests/params.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb, templates/server/puppetserver/conf.d/ca.conf.erb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
closes GH-403
the tests are not ideal, but I think it's better than what was there until now.
=> move authorization and whitelist settings to auth.conf for puppetserver >= 2.2

CHANGELOG.md, README.md, manifests/params.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/web-routes.conf.erb
See https://docs.puppet.com/puppetserver/2.6/release_notes.html#new-feature-jvm-metrics-endpoint-statusv1services
=> add puppetserver 2.6.x support

CHANGELOG.md
Unfortunately I did push the last four commits into 5.0-stable unintentionally. :cry:
In 63b587, the default puppetserver version is set to 2.6.0 now, but I'm unsure if that's bringing more harm or more good, any comments on that?
=> correct typo in changelog (5.0-stable)

templates/server/puppetserver/conf.d/auth.conf.erb
To be used by the smart proxy in #15095.
More info: https://docs.puppet.com/puppetserver/latest/puppet-api/v3/environment_classes.html
=> Permit access to environment_classes Puppet Server API

manifests/params.pp, metadata.json
we can use defined() or getar() here to determine the presence of the
fact. defined() requires puppet3.6, metadata.json currently mentions at
least 3.3. getvar() requires stdlib 4.4, metadata.json currently
mentions at least 4.2. I implemented defined() because this is already
used two lines higher.
=> only set puppetmaster var if fact is available

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp
The $server_facts variable name is reserved by puppet-servers when trusted_server_facts is enabled.
Using this variable in a manifest causes compilation to fail with "Attempt to assign to a reserved variable name: server_facts"
This commit deprecates this variable and introduces the boolean $server_foreman_facts as its replacement.
**Partially** fixes GH issue #440
=> Deprecating and replacing server_facts parameter

manifests/server/config.pp
Other half of https://github.com/theforeman/puppet-foreman/pull/500 because of the the defined() parse order, similar to the foreman_proxy dep.
=> refs #17133 - add puppet::server::config (CA) dep to foreman::service

manifests/server.pp, manifests/server/config.pp, manifests/server/install.pp, manifests/server/passenger.pp, manifests/server/rack.pp, manifests/server/service.pp, spec/classes/puppet_server_rack_spec.rb, spec/classes/puppet_server_service_spec.rb, spec/classes/puppet_server_spec.rb
Includes minor changes to containment of server configuration classes
to ensure notifies of changes from puppet::server::passenger and ::rack
all reach puppet::server::service.
=> fixes #17062 - move master rack restart to puppet::server::service

manifests/server/config.pp, manifests/server/passenger.pp
Fixes errors building the catalog on Puppet 3.6 (e.g. from EPEL7):
=> Fix contain() compatibility with Puppet 3.6 (PUP-1597)

manifests/init.pp
Supported since Kafo 1.0.0, it performs more precise validation of
parameter values and can later be moved to the parameter definitions
when the module is made Puppet 4-only.
=> Change existing Kafo type definitions to Puppet 4 types

metadata.json
It will be EOLed at 2016-12-31 and there are no version based differences in this module, so this will reduce the test run time a little bit.
=> desupport FreeBSD 9.x

manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
set the vardir, logdir and rundir in puppet.conf, so values are equal to puppetserver/conf.d/puppetserver.conf
see: https://docs.puppet.com/puppetserver/2.7/puppet_conf_setting_diffs.html#overriding-puppet-settings-in-puppet-server
PS:
I have a really hard time testing this with foreman-installer. Help is much appreciated.
=> fixes #17634 - set vardir, rundir and logdir explicit in puppet.conf

manifests/config.pp, manifests/params.pp, spec/classes/puppet_config_spec.rb
Ref: #465 
Some times it is possible for the domain fact to be null
these changes address such an instance, sometimes...
On puppet version < 3.7.5 due to the absence of a defined function we
hope for the best and insist that strict variables is disabled.
Evaluating defined('$::domain') before assigning it to srv_domain
=> addressing use cases where $::domain fact is null

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb, templates/server/puppetserver/conf.d/webserver.conf.erb
Change allows the CRL to be enabled when puppet_ca is disabled
additionally provided the ability to sync from the master of masters
the #{ssldir}/ca/ca_crl.pem contents to #{ssldir}/crl.pem. The one side
note is i chose to not notify the puppetserver service every time the
crl.pem file is updated. This could cause undesired downtime of the
compile masters. Reference #460 for additional information.
=> 460 - allow enabling crl when server_ca => false

.sync.yml, Gemfile, spec/acceptance/nodesets/centos-6-x64.yml, spec/acceptance/nodesets/centos-6-x64_docker.yml, spec/acceptance/nodesets/centos-7-x64.yml, spec/acceptance/nodesets/centos-7-x64_docker.yml, spec/acceptance/puppetserver_latest_spec.rb, spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb, spec/spec_helper_acceptance.rb
I've written simple tests with [beaker-rspec](https://github.com/puppetlabs/beaker-rspec) to play with the module. 
Is it of any interest for you?
Run tests one by one with:
```
PUPPET_INSTALL_TYPE=agent \
BEAKER_set=centos-7-x64_docker \
bundle exec rspec spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
PUPPET_INSTALL_TYPE=agent \
BEAKER_set=centos-6-x64_docker \
bundle exec rspec spec/acceptance/puppetserver_latest_spec.rb
```
Further  `BEAKER_*` env params:
* `BEAKER_destroy=no`: don't delete docker process after finishing the test. Can afterwards be inspected with `docker exec -i $ID /bin/bash`
* `BEAKER_provision=no`: don't re-initialize - works for me with vagrant+virtualbox but not with docker
* `BEAKER_debug=yes`: verbose output of whats going on
=> Acceptance tests with beaker-rspec

manifests/server.pp
This allows the CRL checking to be disabled when server_ca is enabled.
Useful for users who have an external CA configured.
=> Allow disabling crl when server_ca => true

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
fixes #479 
To enable external certifacte and key handling add a new boolean to disable the standard private_key
=> Add toggle to disable ssl key handling

manifests/params.pp
This is untested, but should help especially when testing and you don't really need performance but it just needs to be up.
=> Lower JVM heap size when low memory is detected

manifests/init.pp, manifests/params.pp, manifests/server.pp, spec/classes/puppet_server_config_spec.rb
Motivation for the change is to let the user specificity the value of `ssl-cert-chain` in the `webserver.conf` file for puppetserver.
Previously the module hard coded the value of `ssl-cert-chain` to be `${ssl_dir}/ca/ca_crt.pem`.
=> Add optional ssl_chain_filepath option for puppet::server

manifests/params.pp
PSBM is a propritary CentOS 6 from Parallels. It reports osreleasemajor
as 2, not 6.
=> add support for Parallels PSBM

manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb
With `--allow-dns-alt-names` Puppet will use the `dns_alt_names` config option in `puppet.conf` when generating the certificate. 
To test run the installer with `--puppet-dns-alt-names my-other-hostname.example.com,another-name.example.com`, you should then be able to configure an agent to use `my-other-hostname.example.com` & `another-name.example.com` as well as the servers hostname.
=> Fixes #19019 - Generate Puppet cert with --allow-dns-alt-names

manifests/config.pp, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/service.pp, metadata.json, spec/classes/puppet_agent_service_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_spec.rb
1. Moves existing Puppet 4 data types from the class/parameter docs into the class parameters themselves.
1. Converts some older Kafo-only data types into the Puppet 4 style and moves them into the class parameters.
1. Removes the validate_* family of functions, updates a few instances where they had better validation than the data types.
Replaces #485 by adding data types to every parameter.
=> Move existing Puppet 4 data types to class parameters

manifests/init.pp
theforeman-foreman dropped the v1 APIs in 2.2.0. We should not accept
these values anymore.
=> Stop accepting Foreman Puppetmaster v1 APIs

metadata.json
I deployed multiple boxes with freeBSD 11 + puppet agent. works
perfectly.
=> add FreeBSD 11 to metadata.json

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/webserver.conf.erb
This allows configuration of idle timeouts on the Jetty side. A reopening of #484
=> Add web_server_idle_timeout to puppetserver jetty configuration

manifests/server.pp, manifests/server/service.pp, spec/classes/puppet_server_service_spec.rb, spec/classes/puppet_server_spec.rb
When configuring a Passenger-based Puppet master on Debian, installation
of the master package will usually start the service and listen on the
master port. Starting Apache then fails as the port's in use.
This change orders the standalone master resource (with `ensure =>
stopped`) before the Apache service.
=> Order stopping of standalone master service before starting Apache

spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/web-routes.conf.erb
I thought I'd test the Puppet 5 nightly and it turns out that this module breaks the configuration because there is a new endpoint.
This PR fixes the issue, at least enough to allow puppetserver to start correctly. It does require configuring the puppet::server_puppetserver_version parameter to be '5.0.0' explicitly, but that's probably acceptable at this point.
=> Correctly configure the metrics endpoint in web-routes.conf for Puppet server >= 5.0.0

manifests/agent/config.pp, manifests/init.pp, spec/classes/puppet_agent_config_spec.rb
The purpose is to prevent setting of certname.  We use Puppet on systems where the root filesystem is often cloned from other systems and changing certname is cumbersome after a filesystem is cloned.
Default behavior is unchanged.
=> Allow client_certname to be a boolean

manifests/params.pp
When using Puppet 4 with Facter 2 (mostly non-AIO built packages) the following Warning can be seen in the puppetserver log:
```
The string '994.95' was automatically coerced to the numerical value 994.95 at /etc/puppetlabs/code/environments/production/modules/puppet/manifests/params.pp:419:10
The string '994.95' was automatically coerced to the numerical value 994.95 at /etc/puppetlabs/code/environments/production/modules/puppet/manifests/params.pp:423:15
```
=> convert $::memorysize_mb when using facter 2.x

manifests/init.pp
This parameter gets passed to a Package resource.  It should accept a
string or an array of strings.
See https://github.com/theforeman/puppet-puppet/pull/498#discussion_r129916260
=> Fix `client_package` puppet type

templates/server/config.ru.erb
See https://bugs.debian.org/869183
=> Fix "No supported formats are acceptable (Accept: s, pson)" while bucketing from Puppet Agent v3

manifests/server/config.pp
This allows defining `puppet::server::common_modules_path` to work the same as  `puppet::server_common_modules_path`  in the same fashion as the rest of the class parameters for `puppet::server`.
This fix addresses r10k purging $envpath of non-branch directories then puppet creating $envpath/common on each run triggering a refresh of the puppetserver service.
=> update common_modules_path to work in the server::config subclass

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb
Sets the JAVA_ARGS_CLI variable in /etc/sysconfig/puppetserver
This environment variable gets used when `puppetserver gem` is run.
You might need to do this if, for example, your /tmp is mounted with
noexec and you're using the puppetserver_gem package provider...
=> Add server_jvm_cli_args parameter

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb
I'm using octocatalog-diff to fetch catalogs from a puppetserver.
By default, agents can only fetch their own catalogs.  I need to
reconfigure the puppetserver so that octocatalog-diff can fetch
*any* catalog. This commit adds a new
`server_puppetserver_trusted_agents` parameter that makes this possible.
See.
https://github.com/github/octocatalog-diff/blob/master/doc/advanced-puppet-master.md#certificate-authorization
=> Add `puppetserver_trusted_agents` parameter

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/install.pp, spec/classes/puppet_server_config_spec.rb, spec/classes/puppet_server_spec.rb
The use case is that puppet-certs deploys certificates with the owner puppet and now contains a require => Class['puppet::server::install'] but if the User resource is managed then puppet can autorequire it and there is less coupling between modules.
=> Manage the puppet user

spec/classes/puppet_agent_service_cron_spec.rb, spec/classes/puppet_agent_service_systemd_spec.rb
We don't want to rely on facterdb for this value because they don't guarantee it won't change.
Split from https://github.com/theforeman/puppet-puppet/pull/541 since that'll take a bit longer to properly fix.
=> Set a fixed ipaddress fact in ip_to_cron tests

manifests/params.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb, spec/defines/puppet_server_env_spec.rb
since the very first commit with [puppet 4 support](https://github.com/theforeman/puppet-puppet/commit/168ba94ae885acf8b5827a64e2c9609001156c72#diff-2f383a197b1a428561b364755701d60eR84) the shared directory does not seem to be compatible with our [puppet-foreman_scap_client](https://github.com/theforeman/foreman-packaging/blob/rpm/develop/puppet-foreman_scap_client/puppet-foreman_scap_client.spec#L4). We rely on this directory to be included in every environment. I wonder if there's any reason not to keep it to `/usr/share/puppet/modules`? I'd like to avoid changing the packaging definition since the module itself does not really care what puppet version it's being used with.
=> Restore the share directory

manifests/params.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb, spec/defines/puppet_server_env_spec.rb
This is a backport of 9b514e1d85ee407f40377502c8aaeebf261e2806 for the 7.1 branch.
=> [backport] Restore the share directory

.sync.yml, manifests/agent/install.pp, manifests/params.pp, manifests/server/install.pp, manifests/server/service.pp, spec/classes/puppet_agent_install_spec.rb, spec/classes/puppet_agent_service_cron_spec.rb, spec/classes/puppet_agent_service_daemon_spec.rb, spec/classes/puppet_agent_service_spec.rb, spec/classes/puppet_agent_service_systemd_spec.rb, spec/classes/puppet_agent_spec.rb, spec/classes/puppet_config_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_config_spec.rb, spec/classes/puppet_server_passenger_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb, spec/classes/puppet_server_rack_spec.rb, spec/classes/puppet_server_service_spec.rb, spec/classes/puppet_server_spec.rb, spec/defines/puppet_config_entry_spec.rb, spec/defines/puppet_server_env_spec.rb, spec/spec_helper.rb, templates/auth.conf.erb, templates/server/config.ru.erb
We no longer test with Puppet < 4.0 so we can remove that conditional.  It also does some other style improvements.
By setting the ipaddress to a static value we get consistent output from ip_to_cron and don't rely on it to remain unchanged in facterdb.
=> Remove Puppet < 4.5 support

manifests/config.pp
In GH-564 it was pointed out this is not propagated to the actual puppet.conf even though we have a setting for it.
=> Set the codedir in puppet.conf

manifests/params.pp
Only use 2G for puppetserver if at least 3G available. Don't use more than four instances, as 512MB memory per instance are recommended. 
Closes: #571
=> Make performance tuning defaults more safe

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
This commit adds support for queueing and retrying requests if the Puppet
Server is busy.
https://puppet.com/docs/puppet/5.3/release_notes.html#new-feature-puppet-agents-can-retry-requests-on-a-configurable-delay-if-puppet-server-is-busy
Fixes GH-569
=> Add `server_max_queued_requests` and `server_max_retry_delay` parameters

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
Hello,
recently I wanted to try setting puppetserver's compile-mode to some value other than default, your module doesn't as of yet have this functionality. This PR should add it.
=> add compile_mode parameter to puppetserver.conf

manifests/init.pp, spec/classes/puppet_init_spec.rb
Allow httpurl arguments for the pacakge reosurce.
In previous releases this value was not checked and when used with providers like chocolatey, it can support httpurl. The module should not restrict this parameter type so heavily.
=> Allowing the package_source to be an Httpurl

manifests/init.pp
96a514149a35defcfbffefe085a0a9bebf920873 allowed an additional type but it's not matching the case of the type. Somehow the tests do pass so Puppet isn't that particular about it but it looks like Kafo is.
=> Use the correct Stdlib::HTTPUrl

manifests/agent/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_agent_config_spec.rb
This PR adds support for disabling reports
=> Allow reports to be disabled

manifests/agent/service/systemd.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_agent_service_systemd_spec.rb, templates/agent/systemd.puppet-run.timer.erb
Allow configuration of the RandomizedDelaySec parameter of the systemd
timer, which allows randomizing Puppet runs in a way that lets the
administrator see exact moment of the next Puppet run. There's no
incompatibility between Puppet's internal splay and this, but both
probably shouldn't be used together.
This probably still needs adjustments to existing tests.
=> WIP: Add systemd_randomizeddelaysec

manifests/params.pp
This has been tested on the latest Amazon Linux AMI in agent mode. 
Fixes:
`Error: /Stage[main]/Puppet::Agent::Service::Systemd/Service[puppet-run.timer]: Provider systemd is not functional on this host`
I have added "2017" to the regex of $agent_restart_command and $unavailable_runmodes. Without it, the code will try to stop the systemd timer which will fail because systemd is not being used on Amazon Linux (yet).
=> adding support for Amazon Linux

manifests/init.pp, manifests/server.pp
The tests for puppet::server::puppetserver already cover using an array
of strings for this parameter, but the base classes forbid it.
https://github.com/theforeman/puppet-puppet/blob/ee01cffe239c5080c784d17a37a34742fc7db0fe/spec/classes/puppet_server_puppetserver_spec.rb#L823
=> Allow arrays for `server_jvm_extra_args` parameter

manifests/server/puppetserver.pp, spec/classes/puppet_server_config_spec.rb
When the initial puppetserver configs were done, I think there was some confusion about the various TLS settings for puppetserver.  Currently server_ssl_protocols and server_cipher_suites limit what puppetserver [will use as a client](https://github.com/theforeman/puppet-puppet/blob/master/templates/server/puppetserver/conf.d/puppetserver.conf.erb#L81-L95).  To also restrict what the server makes available, it needs to be done in webserver.conf, too.
=> Support ssl-protocols option for puppetserver configuration

manifests/server/puppetserver.pp, spec/classes/puppet_server_config_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/webserver.conf.erb
This reverts commit 64b0cf350124891ecc249790a0732fd4a0f538f4.
=> Revert "use puppetlabs-hocon for webserver.conf"

templates/server/puppetserver/conf.d/metrics.conf.erb
leaving it in breaks your puppet server setup
=> removing redundant > character

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_config_spec.rb, types/custom_trusted_oid_mapping.pp
This commit adds support to configure the
$confdir/custom_trusted_oid_mapping.yaml as described in
https://puppet.com/docs/puppet/5.5/config_file_oid_map.html.
Fixes GH-602
=> Add ability to configure custom_trusted_oid_mapping.yaml

spec/classes/puppet_agent_service_cron_spec.rb, spec/classes/puppet_agent_service_systemd_spec.rb, spec/spec_helper.rb
By default, rspec-puppet-facts uses the facterdb facts that match the
version of the facter gem installed.  Starting with facter 3, facter
was no longer shipped as a gem (it was rewritten in C++).
This commit sets `facterversion` to `3.0.0` so that tests run with
more modern (structured) facts stubbed.
Puppet has been shipping facter 3 since puppet 4.2.0.  This module
supports puppet >= 4.6.1, (and puppet 4 is EOL at the end of 2018).
puppet-extlib's `ip_to_cron` function (used in
puppet::agent::service::cron) has recently moved to using the
`networking` structured fact not available in facter 2.
=> Use facter 3 facts during tests

manifests/agent.pp, manifests/init.pp, manifests/server.pp
This is the current way of containing classes
=> Contain classes

manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
Since 5.3.0 Puppet Server can use some gems shipped by puppet-agent. For
this the gem-path settings of puppetserver.conf needs to be extend by
/opt/puppetlabs/puppet/lib/ruby/vendor_gems. This is the default as
shipped by Puppetlabs.
Fixes GH-630.
=> Add shared gem path for Puppetserver >= 5.3

manifests/params.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb
Updated auth.conf.erb to add support for the "puppet facts upload" command (as introduced in puppetserver v5.5).
See also:
- https://github.com/puppetlabs/puppetserver/blob/master/ezbake/config/conf.d/auth.conf (current default auth.conf)
- https://puppet.com/docs/puppet/5.5/man/facts.html (man page for puppet facts)
- https://tickets.puppetlabs.com/browse/PUP-8232 (Jira issue tickets.puppetlabs.com)
=> updated auth.conf for the "puppet facts upload" command (puppetserver 5.5)

manifests/init.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/webserver.conf.erb
This is based on https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/blob/master/doc/jetty-config.md
=> Add support for managing jetty threads

.fixtures.yml, .sync.yml, .travis.yml, manifests/params.pp, manifests/server/config.pp, spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb, spec/classes/puppet_server_spec.rb
Generated with https://github.com/theforeman/foreman-installer-modulesync/pull/92
=> Add Puppet 6 support

metadata.json
054d079c739f25a6072915c9f2026748fc7c481e omitted this part.
=> Mark as compatible with Puppet 6

spec/classes/puppet_config_spec.rb, spec/defines/puppet_config_entry_spec.rb
This reverts commit dae83420df7cdec1d6551202435634bdd6cf4370.
Looks like Windows platforms are treated the same as Unix again.
=> Revert "Test for the correct line endings on Windows"

manifests/params.pp
* 7a1b62e Remove $deb_naio_package variable
* d22a852 Remove Debian package special case
This was an ancient workaround where puppet didn't properly depend on puppet-common. On Debian Jessie puppet already depends on puppet-common and everything newer has made puppet-common a dummy transitional package. This means we can remove the special case and fall back to the general else case.
=> Remove $deb_naio_package & puppet-common install

manifests/agent/service.pp, manifests/agent/service/cron.pp, manifests/agent/service/daemon.pp, manifests/agent/service/systemd.pp, manifests/init.pp, spec/classes/puppet_agent_spec.rb
=> Add unmanaged Puppet Agent runmode

.fixtures.yml, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/acceptance/puppetserver_config_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
This commit implements the $server_max_open_files parameter which allows
the user to configure the max open file descriptor limit for
Puppetserver.
Fixes #670.
=> Implement $server_max_open_files

manifests/agent/config.pp, manifests/config.pp, spec/classes/puppet_agent_spec.rb, spec/classes/puppet_config_spec.rb
This is needed to ensure all Puppet subcommands can properly use it.
Fixes GH-680.
=> Move client_certname to [main]

manifests/server/config.pp, manifests/server/install.pp, spec/classes/puppet_server_spec.rb
Previously this resulted in a dependency cycle. The tests didn't compile so didn't catch it.
dependency cycles found: (File[/opt/puppetlabs/puppet/cache] => Class[Puppet::Server::Install] => Class[Puppet::Server::Config] => File[/opt/puppetlabs/puppet] => File[/opt/puppetlabs/puppet/cache])
a61e010e8d24f2e44ab1ebba0cc4382b05ce9d37 introduced this by managing $sharedir in puppet::server::config. $vardir was managed in puppet::server::install. Since sharedir is actually /opt/puppetlabs/puppet and vardir is the cache directory within that, it created a cycle.
=> Fixes #26199 - Fix dependency cycle when using git_repo

manifests/agent/config.pp
In Puppet 4 the pluginsync setting was deprecated. At least in Puppet 5 it generates a deprecation warning and in Puppet 6 it was removed.  Because the default was already true, we only emit it if it's non-default to avoid the deprecation warning. In Puppet 6 we can detect an invalid setting so we hard fail.
=> Handle the pluginsync setting deprecation

manifests/params.pp
Amazon Linux now has a 2018 release date on their AMIs:
```
Amazon Linux AMI release 2018.03
Kernel \r on an \m
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2018.03",
major => "2018",
minor => "03"
},
selinux => {
enabled => false
}
}
```
So, when not specifying $agent_restart_command, we get this:
```
Error: /Stage[main]/Puppet::Agent::Service::Systemd/Service[puppet-run.timer]: Provider systemd is not functional on this host
```
=> add 2018 to osreleasemajor for agent_restart_command 

manifests/agent/service.pp, manifests/agent/service/cron.pp, manifests/agent/service/systemd.pp, manifests/init.pp, spec/classes/puppet_agent_spec.rb, templates/agent/systemd.puppet-run.timer.erb
This PR enables you to configure the minute and hour at which your Puppet Cronjob/systemd timer runs.
This is useful for advanced scenarios where you want to limit when the Puppet agent runs.
The change is fully backwards compatible as it does not change any defaults
=> Configurable minute and hour for cronjob and systemd.timer

manifests/agent/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_server_spec.rb
`configtimeout` was deprecated since Puppet 4 and replaced with `http_connection_timeout` and `http_read_timeout`.
=> Use current timeout management variables

README.md
This pull request is to merge changes in files listing module dependencies. Latest version (12.0.0) didn't mention `camptocamp/systemd` module requirement hence when running `puppet module install theforeman-puppet` puppet run failed with the dependency error. 
`README.md` - added new dependency section listing all the dependencies
`metadata.json` - added new values to add dependency for `camptocamp/systemd` module.
=> Document campotocamp/systemd soft dependency

manifests/config.pp, manifests/config/entry.pp, spec/defines/puppet_config_entry_spec.rb
The puppet.conf file doesn't end with a newline which makes it hard to `cat`. This ensure that the file will end with a newline.
=> Ensure config file ends with a new line

manifests/agent.pp
I'm using something like this on **FreeBSD** to manage Puppet Agent...
```
class { 'puppet':
agent                 => true,
agent_restart_command => '/usr/sbin/service puppet restart',
client_package        => 'puppet6',
version               => '6.10.0',
}
```
This works well for normal operation, but when performing an upgrade of Puppet Agent...
```
Info: Applying configuration version '1572887720'
Notice: /Stage[main]/Puppet::Agent::Install/Package[puppet6]/ensure: ensure changed '6.8.1' to '6.10.0' (corrective)
Applied catalog in 8.23 seconds
```
...things start to break. Note that the service was not restarted after performing the package upgrade. This leads to arbitrary errors during all subsequent Puppet Agent runs, here are some of my favorite errors:
```
err   Puppet  Could not …
```
=> Restart Puppet Agent service after updating the package

.sync.yml, .travis.yml
Because of https://github.com/moby/moby/issues/38749 we can't start puppetserver under systemd. That makes all our acceptance tests useless.
=> Stop acceptance tests on EL7

manifests/agent/config.pp, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_config_spec.rb, templates/auth.conf.erb
Puppet 4 dropped puppet run/kick so this code has been dead for some time. It was missed in the big Puppet cleanups.
=> Drop listen parameter

manifests/init.pp
Most parameters are actually not touched by most users. This makes it clear.
=> Move parameters to advanced

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
Puppet Server 6.8 has just been released with an experimental new
feature.
> This release adds a new JRuby pool architecture that maintains a
> single JRuby instance through which requests to Puppet Server are run
> concurrently. In this mode, the server's memory footprint is
> significantly lighter, because it no longer needs to run multiple JRuby
> instances. Toggle this behavior by setting the
> `jruby-puppet.multithreaded` to `true`.
This commit adds support for this new setting.
=> Add server_multithreaded parameter

README.md, manifests/params.pp
This change is needed as puppetlabs is allowing only (non ?)-DH ciphers in puppetdb6, which in turn causes connectivity failures between puppet server and puppetdb if no common cipher is found. Unfortunately, changing the puppet server ciphers is not enough, setting the puppetdb ciphers is also necessary to make sure all communications are ok - this was added in the README in the puppetdb integration section as this change has to be done outside this module.
Fixes GH-714
=> Update cipher suites

.fixtures.yml
Foreman now depends on Redis for the RedisUrl type
=> Add redis as a fixture

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb
Add the server_ca_client_self_delete boolean parameter to CA servers.
When true, allow puppet clients to delete their own certificate from
the Puppet CA.
=> Add server_ca_client_self_delete to CA Servers

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_spec.rb
Make it possible to configure the 'trusted_external_command' parameter.
https://puppet.com/docs/puppet/latest/configuration.html#trustedexternalcommand
Fixes #730.
=> Add server_trusted_external_command parameter

README.md, manifests/agent/service/systemd.pp, metadata.json, spec/classes/puppet_agent_spec.rb, spec/spec_helper_acceptance.rb
This was previously done manually, but there was already a soft dependency on systemd in the server side. This makes it a hard dependency and reuses logic.
Depends on https://github.com/camptocamp/puppet-systemd/pull/119 https://github.com/camptocamp/puppet-systemd/pull/122
Closes GH-704
=> Convert the systemd timer service to camptocamp/systemd

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp
The latest theforeman-foreman has removed these and for older versions they have the only possible value as a default already.
=> Drop Foreman API version parameters

manifests/params.pp, spec/support/aio.rb
This fact is a core fact that's only set on AIO installs. Setting this custom fact is also easier than the structured fact in our test suite which increases reliability of our tests.
Its tests will fail until https://github.com/theforeman/puppet-puppet/pull/735 is merged, but this needs to go in the changelog as a separate entry. IMHO we should merge this if #735 is green.
=> Switch AIO detection to use aio_agent_version fact

.gitignore, CHANGELOG.md, CONTRIBUTING.md, Gemfile, HISTORY.md, Rakefile, manifests/params.pp, spec/classes/puppet_agent_spec.rb, spec/classes/puppet_config_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb, spec/classes/puppet_server_spec.rb, spec/defines/puppet_config_entry_spec.rb, spec/setup_acceptance_node.pp, spec/spec_helper.rb, spec/spec_helper_acceptance.rb, spec/support/aio.rb, spec/support/facts.rb
46c40319775e2293a9e92556fe68755fa348f92d was merged too soon. This makes it work, with the exception of removal of Debian 10 + Puppet 5 (for which no packages are present). That's the only manual change left.
=> Modulesync: make voxpupuli helpers work

README.md, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, manifests/server/puppetdb.pp, spec/classes/puppet_server_puppetdb_spec.rb, spec/classes/puppet_server_spec.rb
Since Puppet 4.0 the active record backend is gone and the only one is PuppetDB. This is the default value for backend is puppetdb so we can simply expose the storeconfigs boolean.
The PuppetDB parameters aren't for the puppetserver itself but rather the puppetdb config in a way that's compatible with this module. Separating it into a class makes it a bit clearer that it really needs an additional Puppet module.
=> Refactor PuppetDB integration

manifests/agent/service/systemd.pp, spec/classes/puppet_agent_spec.rb
This reverts commit 4302973e8f47c77ed35b2a399c1ccef2d503b400, except the dependency bits. It's also updated to be lint clean.
The reason to revert this is that the integrated daemon reload in systemd::timer leads to dependency cycles in the Katello scenario.
=> Revert "Convert the systemd timer service to camptocamp/systemd"

.sync.yml, .travis.yml, metadata.json, spec/acceptance/puppet_spec.rb, spec/acceptance/puppetserver_config_spec.rb, spec/acceptance/puppetserver_latest_spec.rb, spec/acceptance/puppetserver_upgrade_5_3_6_to_5_3_7_spec.rb, spec/acceptance/puppetserver_upgrade_6_7_0_to_6_7_2_spec.rb, spec/setup_acceptance_node.pp, spec/support/acceptance/puppetserver.rb
Fedora 26 is EOL. Fedora 32 is not added since there are no packages available.
=> Add Fedora 31, drop Fedora 26

manifests/server/config.pp, spec/classes/puppet_server_spec.rb
When starting a new puppetserver as CA with existing CA files, the current code tries to perform 'puppetserver ca setup' because the puppetserver's cert does not exist yet.
However, that command fails because the CA cert files exist and can, correctly, not be overwritten.
This PR changes checking for the CA cert, instead of the server's own cert.
=> Don't re-create existing CA certs

manifests/server.pp
Found whilst testing https://github.com/voxpupuli/puppet-lint-param-docs/pull/20
=> Remove unused parameter docs

manifests/agent/service.pp
Looks like #498 had a breaking change when it added an Enum for
`runmode` that didn't include `systemd` (only `systemd.timer`)
But that was a long time ago, so just tidying the code in
`puppet::agent::service`, instead of ammending the `Enum` in `init.pp`.
=> Remove `systemd` from puppet::agent::service case

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp
There are a lot of special use cases for auth.conf, and rather than 100% manage that file, this PR gives the module user a way to provide their own.  Ideally we would use an epp template and also provide a hash of arguments for the template , but I tried to just match the existing pattern in this PR.  This potentially address #752 .
=> adds param for user-provided puppetserver auth.conf

.sync.yml, Gemfile, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb
Accepts an array of hashes to allow for more complicated setups.
Typical use would probably just be a single array element such as...
```puppet
class { 'puppet':
...
server_puppetserver_trusted_certificate_extensions => [{ 'pp_authorization' => 'catalog' }],
...
}
```
=> Add `server_puppetserver_trusted_certificate_extensions`

templates/agent/systemd.puppet-run.service.erb
Using `After` ensures proper ordering between the Puppet service and
the machine's networking. We could also have used `Wants` or
`Requires` but, according to the `systemd.unit(5)` manpage, `After`
only ensure *ordering*, while `Wants` and `Requires`
actually *trigger* units.
In other words, `After` ensures that `puppet-run` will be started
after networking is up, but will not *necessarily* run when networking
is up, nor will it attempt to bring up networking when ran.
Closes: #764
=> run Puppet agent from systemd only after network is brought up

manifests/agent/install.pp, manifests/init.pp, manifests/params.pp, manifests/server/install.pp, spec/classes/puppet_agent_spec.rb, spec/classes/puppet_init_spec.rb, spec/classes/puppet_server_spec.rb
We needed this internally to add the `--diasableexclude=all` flag to the yum install, as puppet* is in the base "exclude=" statement to prevent unintentional upgrade of the puppet agent, by overzealous sysadmins who `yum -y update` I would expect this could be useful in any number of other situations where installation of the package requires specific options being passed to the installer. 
As far as I can tell all supported platforms default package management system supports the `install_options` flag.
=> Add `puppet::package_install_options` variable to allow you to pass flags to package resource

manifests/init.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
This introduces a new parameter to disable the profiling indepently from
the metrics. Previously this was enabled by default. However Puppet Inc.
disables it in their standard configuration and the profiler causes a
significate memory and CPU overhead so I guess we should stick with the
upstream default.
=> (#780) puppetserver: don't purge metrics.conf / Use dedicated parameter for jruby profiler 

manifests/config.pp, manifests/config/entry.pp, spec/defines/puppet_config_entry_spec.rb
This should fix #759.
I start by reverting #707 and re-implementing a fix for it. the actual fix was actually quiet easy, just by adding a concat snippet at the end of each config block with a newline.
=> Fix config append

manifests/agent/service/systemd.pp, metadata.json, spec/classes/puppet_agent_spec.rb
This allows camptocamp/systemd 3.x. Additionally, it goes back to using systemd::timer now that the cyclic dependency can no longer happen.
=> Allow camptocamp/systemd 3.x + use it for timers

manifests/init.pp
Currently the allowed data types for parameter `$package_install_options` do not include arrays. However, when using the chocolatey package provider on Windows, arrays should be used:
https://forge.puppet.com/modules/puppetlabs/chocolatey/readme#packages
=> Improve support for chocolatey package provider on Windows

manifests/agent/config.pp, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, manifests/server/puppetserver.pp, metadata.json, spec/acceptance/puppetserver_latest_spec.rb, spec/acceptance/puppetserver_upgrade_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb, spec/classes/puppet_server_spec.rb, spec/support/acceptance/puppetserver.rb, templates/server/puppetserver/conf.d/auth.conf.erb, templates/server/puppetserver/conf.d/ca.conf.erb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
Replaces https://github.com/theforeman/puppet-puppet/pull/791.
=> Drop Puppet 5 support, require >= 6.15.0 + drop pluginsync & jruby9k parameters

manifests/params.pp, spec/acceptance/hieradata/common.yaml, spec/classes/puppet_agent_spec.rb
This avoids hardcoding the service provider and greatly simplifies the code.
=> Rely on the service_provider fact

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_spec.rb, templates/server/post-receive.erb
This module adds support for the puppet environmentpath setting to be configured
using multiple directories. An example use-case is where r10k is in use to
deploy some but not all environments, to avoid unmanaged environments being
purged by r10k.
- Each listed environmentpath directory will be created and managed by puppet
- The default post-receive hook script uses the first listed directory in
`envs_dir` to create initial environments to maintain backward compatibility.
- The config_version_cmd is updated to use only the first listed directory from
`envs_dir`, this is only used in the environment.conf.erb template which does
not appear to be deployed anywhere in the current version of this module
Tests are included to ensure that all listed directories are created and
managed, and that …
=> Support multiple envs_dir directories

manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb
Puppet does not currently support FIPS on EL8 and needs to be disabled in order to run on a FIPS enabled EL8+ machine within the Java stack. This solution includes the disable flag out right as it does not break on environments where the flag is not present.
A couple questions to consider:
a) should this be a configurable parameter?
b) should this only be included conditionally? (complicates the code a little bit)
=> Disable FIPS support within JVM for Puppet

spec/acceptance/puppetserver_latest_spec.rb
This test is broken, but I can't quite figure out why it's a problem. An [issue](https://github.com/theforeman/puppet-puppet/issues/832) has been opened and this at least allows us to trust CI again.
=> Disable the max open files check on Ubuntu

manifests/init.pp, spec/classes/puppet_server_puppetserver_spec.rb
Puppet Inc. enabled the profiler by default in Puppetserver 5.0.0
https://tickets.puppetlabs.com/browse/SERVER-1761
This module has been disabling by default though causing users to be
missing metrics they might reasonably expect to be present after reading
through the [Puppetserver documentation](https://puppet.com/docs/puppet/6/server/puppet_server_metrics.html#compiler-metrics).
**EDIT**
Also changed `server_puppetserver_metrics` (which enables http-client metrics) to `true`
=> Change `server_puppetserver_profiler` and `server_puppetserver_metrics` defaults to true

manifests/init.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/auth.conf.erb
When set, allows listed clients access to the V2 (jolokia) metrics
endpoint.
See https://puppet.com/docs/puppet/7/server/metrics-api/v2/metrics_api.html
=> Add `server_jolokia_metrics_whitelist` parameter

manifests/agent/service/cron.pp, manifests/agent/service/systemd.pp, manifests/init.pp
If no value for `run_minute` is specified the module internally uses https://forge.puppet.com/modules/puppet/extlib/reference#extlibip_to_cron
This function returns an array of integers as values that then are passed to the cron/systemd timer resources.
Having a list of values is not currently possible if you set the value of `run_minute` via the class.
This change allows specifying the minute you want as an Array of integers.
=> Add Array of Integers as valid type for run_minute

manifests/init.pp, manifests/server.pp, manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb, templates/server/puppetserver/conf.d/puppetserver.conf.erb
=> Add dropsonde telemetry config

manifests/init.pp, manifests/params.pp, manifests/server.pp
TLSv 1.3 support has been in puppetserver since 2019, should be safe to start defaulting to that on.
=> Default to TLS1.3 or TLS1.2 by default since puppet supports both

manifests/agent/config.pp, manifests/init.pp, manifests/params.pp
Also allow override for `localconfig`, but I don't know why someone would change it....
I've been using the default schedules for a few things and, while I get not everyone likes them, I'd like to be able to keep using them.
Without this flag, this module is mostly useless for my environment.
=> Permit setting `default_schedules` to `true`

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/puppet_server_spec.rb
This lets folks easily set owner/group/mode for the content of /etc/puppetlabs/code/environments.
There is a performance cost, but folks opting into this should know that already.
=> Fixes #35983 - Permit recursive ownership/permissions for environments

README.md, manifests/server/config.pp, manifests/server/foreman.pp
This is https://github.com/theforeman/puppet-puppet/pull/801 reopened. The whole effort to build PSF ended up going nowhere for various reasons. This revives the previous effort to it it more user friendly. We can remove the need to pass various parameters for end users, which makes life easier.
Additional PRs will be needed to make use of this.
=> Refs #35985 - Implement optional Katello integration

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_init_spec.rb
There is confidential info in my `puppet.conf` (`http_proxy_password` to be precise) that I would like to secure from unprivileged users.
=> Allow permissions change of puppet.conf

CHANGELOG.md, metadata.json
Apologies, I did dumb things and thought I looked at one thing when I saw another. We had already released 16.4.0 and so this should have been 16.5.0.
=> Release 16.5.0

manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb
This directory is ensured by the puppetserver package and since puppetserver 2.5 the directory that users are supposed to use is in /etc. This code appears tom be a leftover from when the code supported both < 2.5 and >= 2.5 in 68c2d50eac54de1e21e66a96794eca1d1d51f8af.
=> Stop managing services.d dir in /opt/puppetlabs

manifests/server/puppetserver.pp, spec/classes/puppet_server_puppetserver_spec.rb
without it puppetserver will not successfully start.
Fixes: https://github.com/theforeman/puppet-puppet/issues/842
=> Keep ruby's system Gem.dir in gem-path on FreeBSD

manifests/server/config.pp
Previously it was read from the main puppet class, instead of puppet::server (which in turn defaulted to the parameter from the main class).
Fixes #810
=> Respect puppet::server::additional_settings parameter

manifests/params.pp, manifests/server/puppetserver.pp
The upcoming release of Debian will ship with a new non-AIO puppetserver package, and these configuration tweaks are needed to make the module compatible with it.
https://packages.debian.org/search?keywords=puppetserver
=> Support new non-AIO puppet Debian packages

manifests/init.pp, manifests/params.pp
In 2835ba227d5be98d6d7118883c77e7fe9fdd8299 the default `server_ssl_protocols` was expanded to include TLS 1.3.  This had no affect for users not overriding `server_cipher_suites` though as no TLS 1.3 cipher suites were included by default.
This commit adds `TLS_AES_128_GCM_SHA256` and `TLS_AES_256_GCM_SHA384` which are both NIST approved.
=> Add TLS1.3 ciphers to default server_cipher_suites

manifests/init.pp, manifests/params.pp, manifests/server.pp, spec/classes/puppet_server_spec.rb
This default matches what's in theforeman/puppetserver_foreman and is not needed. Users can still override it, but the default just duplicates things.
=> Refs #36573 - Drop default value for foreman_url

.fixtures.yml, README.md, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config.pp, manifests/server/install.pp, spec/classes/puppet_server_spec.rb
This PR switches to using the `puppetlabs/vcsrepo` module.  In theory this should reduce the maintenance overhead of this module for `git` related issues.
=> Fixes #35943 - Switch to puppetlabs vcsrepo for gitrepo tracking

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/puppet_init_spec.rb
In extrernal CA configurations, it is possible that a CRL is not present on the server. This allows to tell the agent to skip downloading it and checking it.
=> Allow disabling CRL checking on agent

spec/acceptance/puppetserver_upgrade_spec.rb, spec/support/acceptance/puppetserver.rb
These days the package is delivered, so it should be verified.
=> Test puppetserver on Debian 11

metadata.json, spec/acceptance/puppetserver_upgrade_spec.rb
also contains https://github.com/theforeman/puppet-puppet/pull/883
=> Add Puppet 8 support

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetserver.pp, templates/server/puppetserver/conf.d/auth.conf.erb, templates/server/puppetserver/conf.d/ca.conf.erb
From https://www.puppet.com/docs/puppet/8/server/http_certificate_renew
=> Add puppet8 certificate renewal endpoint.

manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/install.pp, manifests/server/puppetserver.pp, spec/acceptance/puppetserver_latest_spec.rb, spec/classes/puppet_server_puppetserver_spec.rb
The /usr/bin/java file may point to any version. This changes the logic to determine the java version (unless explicitly specified) dynamically based on the puppetserver version and the OS.
=> Fixes #37291 - Use explicit java on RH with Puppetserver 8

manifests/server/install.pp
In b6088261c08ddfa8d3426ba01c6b35a3d1b1d3a2 ewoud already introduced `stdlib::ensure_packages()`. There's another place that used the legacy `ensure_packages()` function. It's deprecated since stdlib 9. This commit updates the old code to also use `stdlib::ensure_packages()`
=> consistently use stdlib::ensure_packages()

metadata.json
Added AlmaLinux 8 to the supported operating systems in metadata.json.
These changes ensure that we start testing with AlmaLinux 8 and 9 instead of CentOS 8 Stream. This update is part of our transition to better support AlmaLinux in our Puppet modules.
See, for details: https://github.com/theforeman/foreman-infra/issues/2087
=> Add AlmaLinux 8 support

manifests/init.pp
Spotted by @maximevtush in https://github.com/theforeman/theforeman.org/pull/2214.
=> Fix typo in help text: excuted -> executed

manifests/params.pp
This was a workaround for legacy facter versions. The factsets in facterdb, for FreeBSD 11 & 12, all contain the ruby hash.
Removing this workaround removes a legacy fact, which makes the upgrade in https://github.com/theforeman/puppet-puppet/pull/929 easier.
=> Drop legacy FreeBSD 11 workaround

manifests/config.pp
There was a bug in puppet-lint < 4.3 which didn't detect this previously.
https://github.com/puppetlabs/puppet-lint/commit/0e8da67124f293208928a86775bc6f07af28faa4
=> puppet-lint: fix space_before_arrow
