theforeman/puppet-puppet

manifests/init.pp
manifests/params.pp
spec/classes/puppet_agent_spec.rb
templates/agent/puppet.conf.erb

add support for [pre|post]run_command for agent

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/puppet_config_spec.rb
templates/puppet.conf.erb

add module_repository parameter

---

README.md
manifests/init.pp
manifests/params.pp
spec/classes/puppet_agent_spec.rb
spec/classes/puppet_config_spec.rb
templates/agent/puppet.conf.erb
templates/puppet.conf.erb

Additional settings for [main] and [agent] config file sections
... possibly not quite ready yet ;) Let's see how the tests goes.

Extending support for additional settings

---

README.md

This a pull request for issue 254 https://github.com/theforeman/puppet-puppet/issues/254.
Added verbiage around supporting R10K with Directory environment.

Fix readme 4 r10 k

---

.fixtures.yml

This also sorts the repositories

Add file_concat to fixtures.yml

---

manifests/init.pp
manifests/params.pp
manifests/server/config.pp
manifests/server/puppetserver.pp
spec/classes/puppet_init_spec.rb
spec/classes/puppet_server_puppetserver_spec.rb
spec/classes/puppet_server_spec.rb

Comments welcome :) I was unable to run the tests (they all fail). Hopefully travis will do that job for me! :D

Add configuration support for the jvm settings when using puppetserver

---

spec/classes/puppet_config_spec.rb

this fixes the test failures seen with #308

fix FreeBSD tests with rspec-puppet-facts 1.x

---

spec/classes/puppet_config_spec.rb
spec/classes/puppet_server_config_spec.rb
templates/puppet.conf.erb
templates/server/puppet.conf.erb

Fix #311 by moving reports parameter in puppet.conf

---

metadata.json

raise minimum stdlib version

---

manifests/params.pp
spec/classes/puppet_agent_install_spec.rb
spec/classes/puppet_agent_spec.rb
spec/classes/puppet_init_spec.rb

followup to match freebsd/freebsd-ports@53418821

FreeBSD: puppet 3.8.x package got renamed

---

manifests/params.pp

This follows the discussion in https://github.com/theforeman/puppet-foreman/pull/398.

Fix reporting when running under puppet AIO installs

---

manifests/server/install.pp

* Corresponding foreman update: https://github.com/theforeman/puppet-foreman/pull/440
* Corresponding foreman_proxy update: https://github.com/theforeman/puppet-foreman_proxy/pull/246

refs #14942 - order install before foreman/foreman_proxy for puppet group

---

manifests/server/config.pp
spec/classes/puppet_server_config_spec.rb
templates/server/puppet.conf.main.erb

allow undef for $server_common_modules_path

---

manifests/params.pp

see https://tickets.puppetlabs.com/browse/HI-490 for details

change hiera_config back for Puppet >= 4.5

---

manifests/params.pp

Can we have this in 4.3.2?  This seems like a regression that needs fixed.

Added RedHat 5 to  conditionals

---

CHANGELOG.md

Prepare 5.0.0 changelog [skip ci]

---

manifests/init.pp
manifests/params.pp
manifests/server.pp
manifests/server/config.pp
metadata.json
spec/classes/puppet_server_config_spec.rb

even if puppet#15106 was fixed in Puppet 3.3

Don't deploy site.pp on Puppet >= 4.0

---

metadata.json

as the last commit removed the $server_manifest_path parameter.
[skip ci]

bump major version

---

manifests/server/passenger.pp
spec/classes/puppet_server_passenger_spec.rb

Support http to https proxying

---

CHANGELOG.md

Prepare 6.0.0 changelog

---

spec/classes/puppet_server_puppetserver_spec.rb
templates/server/puppetserver/conf.d/auth.conf.erb

add full api path to certificate_status(es) in auth.conf

---

.fixtures.yml
README.md
manifests/server/puppetserver.pp
spec/classes/puppet_server_puppetserver_spec.rb
templates/server/puppetserver/conf.d/auth.conf.erb
templates/server/puppetserver/conf.d/webserver.conf.erb

support http configuration for puppetserver

---

.travis.yml
manifests/params.pp
metadata.json
spec/classes/puppet_agent_config_spec.rb
spec/classes/puppet_agent_service_cron_spec.rb
spec/classes/puppet_agent_service_daemon_spec.rb
spec/classes/puppet_agent_service_spec.rb
spec/classes/puppet_agent_service_systemd_spec.rb
spec/classes/puppet_init_spec.rb
spec/classes/puppet_server_config_spec.rb
spec/classes/puppet_server_passenger_spec.rb
spec/classes/puppet_server_puppetserver_spec.rb
spec/classes/puppet_server_spec.rb
spec/defines/puppet_server_env_spec.rb

Mostly the same as the AIO block. I'm unsure on $sharedir and $server_lenses_dir as I only run Archlinux clients, but these are my best guesses. 
EDIT: forgot tests. looking at that now

Add Archlinux params block for OS defaults

---

CHANGELOG.md

Prepare 7.0.0 changelog

---

.sync.yml
.travis.yml

Uses https://github.com/theforeman/foreman-installer-modulesync/pull/50.

Add Beaker tests to Travis CI config

---

manifests/params.pp

see Debian bug #827867 for details

Debian 9 removed its native puppet-agent package

---

.sync.yml
spec/spec_helper_acceptance.rb

May replace #486, now that master's been modulesynced.

Fix missing acceptance test module dependencies

---

manifests/init.pp

server_package parameter should also take arrays

---

CHANGELOG.md

Add 8.0.0 changelog

---

CHANGELOG.md
metadata.json

There no incompatible changes requiring a major bump.
[ci skip]

Change current version to 7.1.0

---

manifests/agent.pp
manifests/agent/service.pp
manifests/config.pp
manifests/server.pp
manifests/server/config.pp

To match style guide and for compatibility with puppet-lint 2.2.0.

Move chaining arrows to right operand line

---

manifests/init.pp
manifests/params.pp
manifests/server.pp
manifests/server/config.pp
spec/classes/puppet_server_config_spec.rb

This replaces PR #499, it has been rebased to master and squashed.

Add autosign_source, which may be used instead of autosign_content

---

manifests/server/install.pp

fix git integration with theforeman-git 3.0.0

---

manifests/init.pp
manifests/params.pp
manifests/server.pp
manifests/server/puppetserver.pp
spec/classes/puppet_config_spec.rb
spec/classes/puppet_server_puppetserver_spec.rb
templates/auth.conf.erb
templates/server/puppetserver/conf.d/auth.conf.erb
templates/server/puppetserver/conf.d/puppetserver.conf.erb
templates/server/puppetserver/services.d/ca.cfg.erb

this is for discussion, no tests, yet.

Update Puppetserver configurations for 5.0.x

---

CHANGELOG.md

add changelog for 8.0.0

---

README.md
manifests/server.pp

also fixup parameter documentation in server,pp

add puppetserver 5 to README

---

manifests/params.pp
spec/classes/puppet_server_puppetserver_spec.rb
spec/classes/puppet_server_spec.rb

comment and formatting fixes

---

CHANGELOG.md

add 8.0.4 changelog

---

manifests/init.pp

This should clarify the version specification.
Closes GH-472
cc @claflico @jdshewey

Improve documentation around versions

---

CHANGELOG.md
metadata.json

I think this should be 8.1.0 but I'd consider a 9.0 release.

Prepare a 8.1.0 release

---

metadata.json

Whilst browsing the forge I noticed that this new dependency is
formatted differently to all of the others.
https://forge.puppet.com/theforeman/puppet/dependencies
Sorry for my OCD! :)

Cosmetic fix to metadata.json

---

manifests/agent/service/daemon.pp

With Puppet 4 data types we can simplify the complicated case statement to a if/else.

Simplify puppet::agent::daemon

---

manifests/server/puppetserver.pp
spec/classes/puppet_server_puppetserver_spec.rb
templates/server/puppetserver/conf.d/product.conf.erb

This reverts commit 0a45dd1c085192b40012c135fea6f0593eb510b4.

Revert "use puppetlabs-hocon for product.conf"

---

templates/server/puppetserver/conf.d/auth.conf.erb

add status service endpoint

---

spec/classes/puppet_server_puppetserver_spec.rb

This is in preparation of dropping support for puppetserver < 2.7

Refactor puppetserver spec testing

---

manifests/server/puppetserver.pp
spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
spec/classes/puppet_server_puppetserver_spec.rb
templates/server/puppetserver/conf.d/puppetserver.conf.erb

Includes https://github.com/theforeman/puppet-puppet/pull/648

Drop support for puppetserver < 2.7

---

manifests/config.pp

Quick fix for Windows agent restart loop #678

---

manifests/init.pp

Found when testing https://github.com/voxpupuli/puppet-lint-param-docs/pull/19

Remove duplicate docs

---

.github/workflows/acceptance.yml
.github/workflows/cron.yml
.sync.yml
Gemfile

0dea9a76f79561bebf1bcbae74f2a511a5bd79fa missed these parts.

Complete Github Actions migration

---

.github/workflows/acceptance.yml
.github/workflows/cron.yml
.sync.yml
spec/setup_acceptance_node.pp

This uses the [new template option](https://github.com/theforeman/foreman-installer-modulesync/pull/132) to minimize the diff.

Add excludes to sync.yml

---

manifests/init.pp
manifests/params.pp
manifests/server.pp
manifests/server/puppetserver.pp
spec/classes/puppet_server_puppetserver_spec.rb
templates/server/puppetserver/conf.d/auth.conf.erb

Refs #36620 - Replace whitelist with allowlist

---

metadata.json
templates/server/puppetserver/conf.d/auth.conf.erb

Combination of https://github.com/theforeman/puppet-puppet/pull/897 & https://github.com/theforeman/puppet-puppet/pull/891.

Update to puppetlabs-stdlib 9.x, allow puppetlabs-concat 9.x & puppet-extlib 7.x
